#! /usr/bin/env python
# encoding: utf-8
# Ricard Marxer 2008

def set_options(opt):
	opt.tool_options('g++')

def configure(conf):
	conf.check_tool('g++')
        
def build(bld):
        obj = bld.new_task_gen(
                features = ['cxx', 'cprogram'],
                uselib = 'fftw3',
                source = 'test_addon.cpp',
                target = 'test_addon',
                includes = '.. /home/rmarxer/dev/eigen2',
                uselib_local = 'ricaudio'
        )
        
        
