#! /usr/bin/env python
# encoding: utf-8
# Ricard Marxer 2008

def options(opt):
    pass

def configure(conf):
    conf.load('g++')
    conf.load('doxygen', tooldir='doc')

def build(bld):
    obj = bld.new_task_gen(features = 'doxygen',
                               doxyfile = 'Doxyfile',
                               doxy_tar = 'docs.tar.bz2')
