#! /usr/bin/env python
# encoding: utf-8
# Ricard Marxer 2008


def set_options(opt):
	opt.tool_options('compiler_cxx')
       	opt.tool_options('python')

def configure(conf):
	conf.check_tool('compiler_cxx python')
        conf.check_python_version((2,4,2))
	conf.check_python_headers()
	conf.check_tool('swig', tooldir = '/home/rmarxer/dev/ricaudio/src/swig')
	conf.check_swig_version('1.3.27')

        try:
                conf.check_python_module('numpy')
        except Configure.ConfigurationError:
                print "(module ''numpy'' not found, but we ignore it)"
        
	conf.env.append_value('CXXFLAGS', '-O3 -fPIC -msse2 -DRICAUDIO_DEBUG')
        conf.env.append_value('LINKFLAGS', '-lfftw3f')

def build(bld):
        obj = bld.new_task_gen(
                features = ['cxx', 'pyembed'],
                source = 'ricaudio.i',
                target = 'ricaudio',
                swig_flags = '-c++ -python -Wall -I/home/rmarxer/dev/eigen2',
                swig_includes = '.. /home/rmarxer/dev/eigen2',
                includes = '.. /home/rmarxer/dev/eigen2',
                name         = 'pyricaudio',
                want_libtool = 1,
                vnum         = '0.1',
                uselib_local = 'ricaudio',
        )        

        obj.find_sources_in_dirs('..', exts=['.cpp'])
        print obj.source
