#! /usr/bin/env python
# encoding: utf-8
# Ricard Marxer 2008

LIBNAME = 'ricaudio'
LIBVERSION = '0.1-dev'


def set_options(opt):
	opt.tool_options('compiler_cxx')

        opt.sub_options('swig')
        opt.sub_options('tests')

def configure(conf):
	conf.check_tool('compiler_cxx')

	conf.env.append_value('CXXFLAGS', '-O3 -fPIC -msse2 -DNDEBUG')
	#conf.env.append_value('CXXFLAGS', '-O3 -fPIC -msse2 -DRICAUDIO_DEBUG')
        conf.env.append_value('LINKFLAGS', '-lfftw3f')

        conf.sub_config('swig')
        conf.sub_config('tests')


def build(bld):
        obj = bld.new_task_gen(
                features = 'cxx cshlib',
                uselib = 'fftw3',
                target = LIBNAME,
                includes = '. /home/rmarxer/dev/eigen2',
                export_inc_dirs = '.',
                name         = LIBNAME,
                vnum         = LIBVERSION
        )
        
	obj.find_sources_in_dirs('.', exts=['.cpp'])
        
	bld.add_subdirs('swig')
        bld.add_subdirs('tests')
        
        #bld.install_files('${PREFIX}/include/ricaudio', 'aok.h')
